#docker-compose.yml
# Use root/example as user/password credentials
version: '3.5'
name: retry-view-project

services:
  db:
    image: mysql:8.0.39
    restart: always
    ports:
    - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root1234
    networks:
    - retry-view-network
  api:
    image: pjiwon7/retry-view-api:0.1
    ports:
    - 8080:8080
    depends_on:
    - db
    - redis
    build:
      context: ./app
      dockerfile: Dockerfile
      # args:
    networks:
    - retry-view-network
  redis:
    image: redis:7.4.1
    ports:
    - 6379:6379
    command: redis-server
    networks:
    - retry-view-network

networks:
  retry-view-network:
    external: true
